variables:
  REGISTRY_HOST: hub.irontec.com

stages:
  - build

build:
  stage: build
  tags:
    - runners
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t $REGISTRY_HOST/$CI_PROJECT_PATH:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:latest

